# Generated by Django 5.2.17 on 2026-09-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("dates", models.CharField(blank=True, default="", max_length=255)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=10)),
                (
                    "sustainability_level",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("destination_lat", models.FloatField(blank=True, null=True)),
                ("destination_lon", models.FloatField(blank=True, null=True)),
                ("fallback_count", models.PositiveIntegerField(default=0)),
                ("handed_over", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
