# Generated by Django 5.2.17 on 2026-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="dates",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="fallback_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="session_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="sustainability_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
